package krystiankatafoni.retailrecommendationsystem.services.generic;

import krystiankatafoni.retailrecommendationsystem.domain.ProductWithSearchScore;

public interface ProductFullTextSearchService extends FullTextSearchService<ProductWithSearchScore>{}
